drop schema public cascade;
create schema public;

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    address character varying(255),
    phone character varying(50),
    email character varying(255),
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE paper (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    discontinued boolean NOT NULL DEFAULT FALSE,
    stock integer NOT NULL DEFAULT 0,
    price double precision NOT NULL,
    CONSTRAINT paper_pkey PRIMARY KEY (id)
);

CREATE TABLE properties (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    property_name character varying(255) NOT NULL,
    CONSTRAINT properties_pkey PRIMARY KEY (id)
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_date timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    --  PSA: I recommend using DateTime.UtcNow for making timestamps with entity framework for the above order_date
    
    delivery_date date,
    status character varying(50) NOT NULL DEFAULT ('pending'::character varying),
    total_amount double precision NOT NULL,
    customer_id integer,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE paper_properties (
    paper_id integer NOT NULL,
    property_id integer NOT NULL,
    CONSTRAINT paper_properties_pkey PRIMARY KEY (paper_id, property_id),
    CONSTRAINT paper_properties_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES paper (id),
    CONSTRAINT paper_properties_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties (id)
);

CREATE TABLE order_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    quantity integer NOT NULL,
    product_id integer,
    order_id integer,
    CONSTRAINT order_entries_pkey PRIMARY KEY (id),
    CONSTRAINT order_entries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT order_entries_product_id_fkey FOREIGN KEY (product_id) REFERENCES paper (id)
);

CREATE UNIQUE INDEX customers_email_key ON customers (email);
CREATE INDEX "IX_order_entries_order_id" ON order_entries (order_id);
CREATE INDEX "IX_order_entries_product_id" ON order_entries (product_id);
CREATE INDEX "IX_orders_customer_id" ON orders (customer_id);
CREATE UNIQUE INDEX unique_product_name ON paper (name);
CREATE INDEX "IX_paper_properties_property_id" ON paper_properties (property_id);

-- Insert sample customers
INSERT INTO customers (name, address, phone, email)
VALUES
('Michael Scott', 'Condo 126, Scranton, PA', '570-555-1234', 'michael.scott@dundermifflin.com'),
('Pam Beesly', '459 Maple Avenue, Scranton, PA', '570-555-5678', 'pam.beesly@dundermifflin.com'),
('Jim Halpert', '1120 Mulberry Lane, Scranton, PA', '570-555-9876', 'jim.halpert@dundermifflin.com'),
('Dwight Schrute', 'Schrute Farms, Honesdale, PA', '570-555-4321', 'dwight.schrute@dundermifflin.com');

-- Insert sample paper products
INSERT INTO paper (name, discontinued, stock, price)
VALUES
('Dunder Mifflin Copy Paper', FALSE, 500, 29.99),
('Dunder Mifflin Premium Paper', FALSE, 300, 49.99),
('Dunder Mifflin Recycled Paper', FALSE, 200, 39.99),
('Dunder Mifflin Glossy Paper', TRUE, 0, 59.99);

-- Insert sample properties
INSERT INTO properties (property_name)
VALUES
('High Brightness'),
('Recycled Material'),
('Glossy Finish'),
('Heavyweight');

-- Insert sample paper_properties (assigning properties to papers)
INSERT INTO paper_properties (paper_id, property_id)
VALUES
(1, 1), -- Dunder Mifflin Copy Paper - High Brightness
(2, 1), -- Dunder Mifflin Premium Paper - High Brightness
(2, 4), -- Dunder Mifflin Premium Paper - Heavyweight
(3, 2), -- Dunder Mifflin Recycled Paper - Recycled Material
(4, 3); -- Dunder Mifflin Glossy Paper - Glossy Finish

-- Insert sample orders
INSERT INTO orders (order_date, delivery_date, status, total_amount, customer_id)
VALUES
('2024-09-21 19:48:55.922163+00', '2024-09-28', 'shipped', 149.97, 1), -- Michael Scott's order
('2024-09-22 19:48:55.922163+00', '2024-10-01', 'pending', 99.98, 2), -- Pam Beesly's order
('2024-09-24 19:48:55.922163+00', '2024-09-25', 'delivered', 59.99, 3); -- Jim Halpert's order

-- Insert sample order_entries (line items in orders)
INSERT INTO order_entries (quantity, product_id, order_id)
VALUES
(3, 1, 1), -- Michael Scott ordered 3x Dunder Mifflin Copy Paper
(2, 2, 2), -- Pam Beesly ordered 2x Dunder Mifflin Premium Paper
(1, 3, 3); -- Jim Halpert ordered 1x Dunder Mifflin Recycled Paper